In [ ]:
##Weather_Database.ipynb

In [8]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import weather_api_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [17]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
hotel_df = pd.read_csv("vacation_search/WeatherPy_vacation.csv")
# vacation_df = pd.read_csv("Vacation_Search/WeatherPy_vacation.csv")
hotel_df
# vacation_df.head()

,hotel_df,City,Country,Max Temp,Lat,Lng,Hotel Name
0,5,Umm Lajj,SA,82.940,25.0213,37.2685,Moon light Furnished Units
1,10,Rikitea,PF,77.036,-23.1203,-134.9692,People ThankYou
2,12,Puerto Ayora,EC,77.234,-0.7393,-90.3518,Finch Bay Galapagos Hotel
3,17,Vaini,TO,81.032,-21.2000,-175.2000,Keleti Beach Resort
4,24,Acarau,BR,79.808,-2.8856,-40.1200,castelo pizzaria
...,...,...,...,...,...,...,...
181,555,Mexico,PH,80.582,15.0646,120.7198,stone place
182,564,Alta Floresta,BR,77.180,-9.8756,-56.0861,Floresta Amazonica Hotel
183,567,Jieshi,CN,76.100,22.8134,115.8257,Yuehai Hotel
184,572,Kloulklubed,PW,75.974,7.0419,134.2556,Storyboard Beach Resort
185,584,Pundaguitan,PH,80.006,6.3711,126.1689,Leonardo Family Beach House 1

In [48]:
lat = -23.1203
lng = -134.9692
url = f"https://api.openweathermap.org/data/2.5/weather?appid={weather_api_key}"
url_call = f"{url}&lat={lat}&lon={lng}"
test = requests.get(url_call)
test_json = test.json()
test_json["weather"]

TypeError: list indices must be integers or slices, not set

In [71]:
test_json['weather'][0]['description']

'light rain'

In [80]:
len(hotel_df)

186

In [93]:
for row in hotel_df:
    lat = row["Lat"]
    lng = row["Lng"]
    url = f"https://api.openweathermap.org/data/2.5/weather?appid={weather_api_key}"
    print(f"Processing Record {record_count} of Set {set_count} | {lat}, {lng}")
    record_count += 1
    url_call = f"{url}&lat={lat}&lon={lng}"

    url_call = requests.get(url_call)
    url_json = url_call.json()
    description = url_json['weather'][0]['description']
    row['description'] = description  


# Indicate that Data Loading is complete.
print("-----------------------------")
print("Data Retrieval Complete      ")
print("-----------------------------")

TypeError: string indices must be integers

In [89]:
hotel_df

,hotel_df,City,Country,Max Temp,Lat,Lng,Hotel Name
0,5,Umm Lajj,SA,82.940,25.0213,37.2685,Moon light Furnished Units
1,10,Rikitea,PF,77.036,-23.1203,-134.9692,People ThankYou
2,12,Puerto Ayora,EC,77.234,-0.7393,-90.3518,Finch Bay Galapagos Hotel
3,17,Vaini,TO,81.032,-21.2000,-175.2000,Keleti Beach Resort
4,24,Acarau,BR,79.808,-2.8856,-40.1200,castelo pizzaria
...,...,...,...,...,...,...,...
181,555,Mexico,PH,80.582,15.0646,120.7198,stone place
182,564,Alta Floresta,BR,77.180,-9.8756,-56.0861,Floresta Amazonica Hotel
183,567,Jieshi,CN,76.100,22.8134,115.8257,Yuehai Hotel
184,572,Kloulklubed,PW,75.974,7.0419,134.2556,Storyboard Beach Resort
185,584,Pundaguitan,PH,80.006,6.3711,126.1689,Leonardo Family Beach House 1

In [ ]:
city_data = []
print("Beginning Data Retrieval     ")
print("-----------------------------")
record_count = 1
set_count = 1
# Loop through all the cities in the list.
for i, city in enumerate(cities):

    # Group cities in sets of 50 for logging purposes.
    if (i % 50 == 0 and i >= 50):
        set_count += 1
        record_count = 1
        time.sleep(60)

    # Create endpoint URL with each city.
    city_url = url + "&q=" + city.replace(" ","+")

    # Log the URL, record, and set numbers and the city.
    print(f"Processing Record {record_count} of Set {set_count} | {city}")
    # Add 1 to the record count.
    record_count += 1
    # Run an API request for each of the cities.
    try:
        # Parse the JSON and retrieve data.
        city_weather = requests.get(city_url).json()
        # Parse out the needed data.

        # Convert the date to ISO standard.
        city_date = datetime.utcfromtimestamp(city_weather["dt"]).strftime('%Y-%m-%d %H:%M:%S')
        # Append the city information into city_data list.
        city_data.append({"City": city.title(),
                          "Lat": city_lat,
                          "Lng": city_lng,
                          "Max Temp": city_max_temp,
                          "Humidity": city_humidity,
                          "Cloudiness": city_clouds,
                          "Wind Speed": city_wind,
                          "Country": city_country,
                          "Date": city_date})

# If an error is experienced, skip the city.
    except:
        print("City not found. Skipping...")
        pass

# Indicate that Data Loading is complete.
print("-----------------------------")
print("Data Retrieval Complete      ")
print("-----------------------------")